## Dependencies

In [1]:
import pandas as pd
import os

## Tranform data

In [2]:
def transform_data(eng_path,ger_path):

    with open(eng_path, "r", encoding="utf-8") as eng_file:
        english_file = eng_file.readlines()

    with open(ger_path, "r", encoding="utf-8") as ger_file:
        german_file = ger_file.readlines()

    data = {
        "English": [line.strip() for line in english_file],
        "German": [line.strip() for line in german_file],
    }
    return pd.DataFrame(data)

def save_file(df,filename,output_path = "./data"):
    filepath = os.path.join(output_path,filename)
    return df.to_csv(path_or_buf=filepath,index=False,encoding="utf-8")

### Train data

In [5]:
train_data = transform_data(eng_path="./data/train.en",ger_path="./data/train.de")
save_file(df=train_data,filename="train_data.csv")

In [11]:
train_data

,English,German
0,"Two young, White males are outside near many b...",Zwei junge weiße Männer sind im Freien in der ...
1,Several men in hard hats are operating a giant...,Mehrere Männer mit Schutzhelmen bedienen ein A...
2,A little girl climbing into a wooden playhouse.,Ein kleines Mädchen klettert in ein Spielhaus ...
3,A man in a blue shirt is standing on a ladder ...,Ein Mann in einem blauen Hemd steht auf einer ...
4,Two men are at the stove preparing food.,Zwei Männer stehen am Herd und bereiten Essen zu.
...,...,...
28996,A rock climber practices on a rock climbing wall.,Ein Bergsteiger übt an einer Kletterwand.
28997,Two male construction workers are working on a...,Zwei Bauarbeiter arbeiten auf einer Straße vor...
28998,An elderly man sits outside a storefront accom...,Ein älterer Mann sitzt mit einem Jungen mit ei...
28999,A man in shorts and a Hawaiian shirt leans ove...,Ein Mann in Shorts und Hawaiihemd lehnt sich ü...
29000,,

### Validation data

In [8]:
val_data = transform_data(eng_path="./data/val.en",ger_path="./data/val.de")
save_file(df=val_data,filename="val_data.csv")

In [13]:
val_data

,English,German
0,A group of men are loading cotton onto a truck,Eine Gruppe von Männern lädt Baumwolle auf ein...
1,A man sleeping in a green room on a couch.,Ein Mann schläft in einem grünen Raum auf eine...
2,A boy wearing headphones sits on a woman's sho...,Ein Junge mit Kopfhörern sitzt auf den Schulte...
3,Two men setting up a blue ice fishing hut on a...,Zwei Männer bauen eine blaue Eisfischerhütte a...
4,A balding man wearing a red life jacket is sit...,"Ein Mann mit beginnender Glatze, der eine rote..."
...,...,...
1010,A bunch of police officers are standing outsid...,Eine Gruppe von Polizisten steht vor einem Bus.
1011,A elderly white-haired woman is looking inside...,Eine ältere weißhaarige Frau sieht in ihre Kas...
1012,Two men are standing at telephone booths outside.,Zwei Männer stehen an Telefonzellen im Freien.
1013,Two women wearing red and a man coming out of ...,"Zwei Frauen in Rot und ein Mann, der aus einer..."
1014,,

### Test data

In [16]:
test_data = transform_data(eng_path="./data/test.en",ger_path="./data/test.de")

with open("./data/test.fr","r",encoding="utf-8") as fr_file:
    french_file = fr_file.readlines()

test_data['French'] = [line.strip() for line in french_file]
save_file(df=test_data,filename="test_data.csv")

In [17]:
test_data

,English,German,French
0,A man in an orange hat starring at something.,"Ein Mann mit einem orangefarbenen Hut, der etw...",Un homme avec un chapeau orange regardant quel...
1,A Boston Terrier is running on lush green gras...,Ein Boston Terrier läuft über saftig-grünes Gr...,Un terrier de Boston court sur l'herbe verdoya...
2,A girl in karate uniform breaking a stick with...,Ein Mädchen in einem Karateanzug bricht ein Br...,Une fille en tenue de karaté brisant un bâton ...
3,Five people wearing winter jackets and helmets...,Fünf Leute in Winterjacken und mit Helmen steh...,Cinq personnes avec des vestes d'hiver et des ...
4,People are fixing the roof of a house.,Leute Reparieren das Dach eines Hauses.,Des gens réparent le toit d'une maison.
...,...,...,...
995,"Marathon runners are racing on a city street, ...",Marathonläuferinnen laufen auf einer städtisch...,Des marathoniens font une course dans une rue ...
996,Asian woman wearing a sunhat while riding a bike.,Asiatische Frau trägt einen Sonnenhut beim Fah...,Une femme asiatique avec un chapeau faisant du...
997,Some children are outside playing in the dirt ...,Ein paar Kinder sind im Freien und spielen auf...,"Des enfants sont dehors, jouant dans la terre ..."
998,An older man is playing a video arcade game.,Ein älterer Mann spielt ein Videospiel.,Un vieil homme joue sur une borne d'arcade.
999,A girl at the shore of a beach with a mountain...,Ein Mädchen an einer Küste mit einem Berg im H...,Une fille au bord d'une plage avec une montagn...